image:
  tag: 1.2.0

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: "letsencrypt-production"
  path: /
  hosts:
    # TODO: Change this back
    - example.test
  tls:
    - secretName: ca--tls
      hosts:
        # TODO: Change this back
        - example.test

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi

caName: ca

postgresql:
  enabled: false

config:
  hlfToolsVersion: 1.2.0
  csr:
    names:
      c: MY
      st: KL
      l:
      o: "mytech"
      ou: Blockchain
  affiliations:
    mytech: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 95
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels:
