fullnameOverride: ca-orderer-hlf-ca
nodeName: ca
orgName: orderer

maintenanceMode: false

image:
  tag: 1.4.8

ingress:
  enabled: false

persistence:
  enabled: true
  storageClass: standard
  accessMode: ReadWriteOnce
  size: 1Gi

replicas: 1
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 95
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels:         
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app: postgresql
          release: ca
      topologyKey: "kubernetes.io/hostname"            
caName: ca-orderer

externalDatabase:
  type: postgres
  host: postgres-postgresql
  port: 5432
  username: root
  password: db_password
  database: fabric_ca
  ssl-mode: disable 

config:
  hlfToolsVersion: 1.4.8
  debug: false
  enableTLSWithoutIngress: true
  useIssuedTLS: true
  useIssuedCACert: true

csrHosts: ca-orderer,ca-orderer-hlf-ca,ca-orderer-hlf-ca.bc.svc.cluster.local,localhost
