image:
  tag: 1.2.0

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi

ord:
  type: raft
  ## MSP ID of the Orderer
  mspID: MSP

secrets:
  ord:
    cert: hlf--ord-idcert
    key: hlf--ord-idkey
    caCert: hlf--ca-cert
  genesis: hlf--genesis
  adminCert: hlf--org-admincert
  caServerTls: ca--tls

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 95
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels:
              app: hlf-ord
