fullnameOverride: orderer0-hlf-ord
nodeName: orderer0
orgName: orderer

maintenanceMode: false

image:
  tag: 2.2.0

persistence:
  enabled: true
  storageClass: standard
  accessMode: ReadWriteOnce
  size: 1Gi

ord:
  type: raft
  mspID: orderer
  tls:
    server:
      enabled: "true"
affinity:
  nodeAffinity:

secrets:
  ord:
    cert: hlf--orderer0-orderer-idcert
    key: hlf--orderer0-orderer-idkey
    caCert: hlf--orderer0-orderer-cacert
    tls: hlf--orderer0-orderer-tls
    tlsRootCert: hlf--orderer0-orderer-tlsrootcert
  genesis: hlf--genesis
  adminCert: hlf--orderer0-orderer-admincert
